volumes:
  mysqldata:

services:
  db:
    container_name: db
    image: mariadb:10.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=your-root-pw
      - MYSQL_USER=your-mysql-user
      - MYSQL_PASSWORD=your-mysql-user-pw
      - MYSQL_DATABASE=your-initial-db
    volumes:
      # ...volume for the database
      - mysqldata:/var/lib/mysql

      # ...path to custom MySQL configuration files
      - ./conf.d:/etc/mysql/conf.d

      # ...folder containing initial database dumps to populate the database
      - ./dumps:/docker-entrypoint-initdb.d

      # ...a place to put data into the running container if needed
      - ./shared:/shared
    ports:
      - 3306:3306