volumes:
  mysqldata:

services:
  db:
    container_name: mariadb
    image: mariadb:10.6
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # ...volume for the database
      - mysqldata:/var/lib/mysql

      # ...directory containing db import- and export scripts
      - ./scripts/dump:/opt/mysql/scripts/dump

      # ...a place to put data into the running container if needed
      - ./shared:/shared
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    ports:
      - 3306:3306