set windows-powershell := true

# List available commands
default:
	@just --List

# Start docker container
start-docker:
	docker-compose up

# Remove docker container
clean-docker:
	docker-compose down
	docker volume rm mariadb-10-6_mysqldata

# Enter mysql
enter-mysql:
	docker exec -it mariadb mysql -uroot -p1234

# Execute sql script
db-execute:
	docker exec -it mariadb /opt/mysql/scripts/db-execute.sh

# Export dump
db-export:
	docker exec -it mariadb /opt/mysql/scripts/db-export.sh
