set windows-powershell := true

# List available commands
default:
	@just --List

# Start docker container
start-docker:
	docker-compose up

# Remove docker container
clean-docker:
	docker-compose down
	docker volume rm mariadb-10-6_mysqldata

# Enter mysql
enter-mysql:
	docker exec -it mariadb mysql -uroot -p1234

# Execute sql script
execute-sql:
	docker exec -it mariadb /opt/mysql/scripts/sql/execute.sh

# Export dump
export-dump:
	docker exec -it mariadb /opt/mysql/scripts/dump/export.sh