volumes:
  oradata:

services:
  db:
    container_name: oracle
    image: container-registry.oracle.com/database/free:23.3.0.0
    volumes:
      # ...volume for the database and required database configuration files
      - oradata:/opt/oracle/oradata

      # ...directory containing db import- and export scripts
      - ./scripts/dump:/opt/oracle/scripts/dump

      #...a place to put data into the running container if needed
      - ./shared:/shared
    environment:
      - ORACLE_PWD=1234
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - 1521:1521
      - 5500:5500
