set windows-powershell := true

# List available commands
default:
	@just --List

# Start docker container
start-docker:
	docker-compose up

# Remove docker container
clean-docker:
	docker-compose down
	docker volume rm oracle-free-23_oradata

# Enter sqlplus
enter-sqlplus:
	docker exec -it oracle sqlplus sys/1234@localhost:1521/FREEPDB1 as sysdba

# Execute sql script
execute-sql:
	docker exec -it oracle /opt/oracle/scripts/sql/execute.sh

# Import dump
import-dump:
	docker exec -it oracle /opt/oracle/scripts/dump/import.sh

# Export dump
export-dump:
	docker exec -it oracle /opt/oracle/scripts/dump/export.sh