set windows-powershell := true

# List available commands
default:
	@just --List

# Start docker container
start-docker:
	docker-compose up

# Remove docker container
clean-docker:
	docker-compose down
	docker volume rm oracle-free-23_oradata

# Enter sqlplus
enter-sqlplus:
	docker exec -it db sqlplus sys/oracle@localhost:1521/FREEPDB1 as sysdba

# Import dump
db-import:
	docker exec -it db /opt/oracle/scripts/dump/import.sh

# Export dump
db-export:
	docker exec -it db /opt/oracle/scripts/dump/export.sh
