set windows-powershell := true

# List available commands
default:
	@just --List

# Start docker container
start-docker:
	docker-compose up

# Remove docker container
clean-docker:
	docker-compose down
	docker volume rm oracle-free-23_oradata

# Enter sqlplus
enter-sqlplus:
	docker exec -it oracle sqlplus sys/1234@localhost:1521/FREEPDB1 as sysdba

# Import dump
db-import:
	docker exec -it oracle /opt/oracle/scripts/db-import.sh

# Export dump
db-export:
	docker exec -it oracle /opt/oracle/scripts/db-export.sh
	
# Execute sql script
db-execute:
	docker exec -it oracle /opt/oracle/scripts/db-execute.sh
